Remove implicit Poolitem to bool conversion.
This patch fixes below error when we build with latest libzypp. This
patch cherry-picked from
https://github.com/openSUSE/zypper/commit/44ef7fb29eed20a276aa09dae2353e2e78845aad

[  103s] /home/abuild/rpmbuild/BUILD/zypper-1.8.14/src/search.cc:672:28:
error: cannot convert 'zypp::PoolItem' to 'bool' in initialization
[  103s]      bool missedInstalled = installed; // if no available hits,
we need to print it

Change-Id: Ice81d4cd9d7f7f063876f4965393e3c6f0a10a16
Signed-off-by: Chanho Park <chanho61.park@samsung.com>